// packages/design-core/src/previewReact/src/srcFiles/login.jsx
import React from 'react'

const Login = () => {
  const url = React.useRef('')
  return (
    <div style={{ position: 'fixed', zIndex: 999, top: 0, right: 0, bottom: 0, left: 0, backgroundColor: '#fff' }}>
      <iframe src={url.current} frameBorder="0" style={{ width: '100%', height: '100%' }}></iframe>
    </div>
  )
}

export default Login

// packages/design-core/src/preview/src/preview/srcFiles/Login.vue
<template>
  <div class="login-wrapper">
    <iframe :src="url" class="login-iframe" frameBorder="0" scrolling="no"></iframe>
  </div>
</template>

<script>
export default {
  setup() {
    const url = ''

    return {
      url
    }
  }
}
</script>

<style scoped>
.login-wrapper {
  position: fixed;
  z-index: 999;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: #fff;
}
.login-iframe {
  width: 100%;
  height: 100%;
}
</style>
